-- orange-learn -> Supabase PostgreSQL
-- Generated from database/orange_learn.db

create table if not exists public.materi (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text not null,
  deskripsi text,
  isi text,
  tingkat text,
  urutan integer default 0
);

create table if not exists public.widget (
  id bigint generated by default as identity primary key,
  nama text not null,
  kategori text not null,
  deskripsi text,
  fungsi text,
  input_data text,
  output_data text,
  tingkat text,
  contoh text,
  urutan integer default 0
);

create table if not exists public.workflow (
  id bigint generated by default as identity primary key,
  nama text not null,
  kategori text not null,
  tujuan text,
  deskripsi text,
  tingkat text,
  urutan integer default 0
);

alter table public.materi enable row level security;
alter table public.widget enable row level security;
alter table public.workflow enable row level security;

drop policy if exists "anon can read materi" on public.materi;
create policy "anon can read materi" on public.materi for select to anon using (true);
drop policy if exists "anon can read widget" on public.widget;
create policy "anon can read widget" on public.widget for select to anon using (true);
drop policy if exists "anon can read workflow" on public.workflow;
create policy "anon can read workflow" on public.workflow for select to anon using (true);

grant select on public.materi, public.widget, public.workflow to anon, authenticated;

